[workspace]
name = "pixi-diff"
channels = ["conda-forge"]
platforms = ["osx-arm64", "osx-64", "linux-64", "linux-aarch64", "win-64"]

[tasks]
build = "cargo build --release"
test = "cargo test"
demo = "vhs .github/assets/demo/demo-light.tape && vhs .github/assets/demo/demo-dark.tape"

[dependencies]
rust = "==1.88.0"
openssl = "*"
pkg-config = "*"
vhs = "*"
glow-md = "*"

[target.linux.dependencies]
compilers = ">=1.7.0"

[feature.lint.dependencies]
pre-commit = "*"
prettier = "*"
taplo = "*"
pre-commit-hooks = "*"
typos = "*"
[feature.lint.tasks]
pre-commit-install = "pre-commit install"
pre-commit-run = "pre-commit run -a"

[environments]
default = ["lint"]
lint = { features = ["lint"], no-default-feature = true }
